# serverless.yml

service:
  name: todo-service
  config:
    accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    zoneId: ${{ secrets.CLOUDFLARE_ZONE_ID }}

provider:
  name: cloudflare

plugins:
  - serverless-cloudflare-workers
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: serverless_django.wsgi.application
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'